# Generated by Django 5.2.15 on 2026-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("IN", "In stock"),
                    ("BO", "Backorder"),
                    ("DC", "Discontinued"),
                ],
                default="IN",
                help_text="Availability from the supplier stock file.",
                max_length=2,
            ),
        ),
    ]
